Wiki Revision "23R2", codename "Towers".
PojavLauncherTeam/pojavlauncherteam.github.io pull request #106
Opened 2023-11-01 14:57 UTC by xenophiee

```
As this Pull Request will be actively worked on, the following push out date of this PR will be paused for a while:

PR #82 "EULA | Part 1".

Work on the aforementioned PR will be resumed after the push of this PR to the main branch.
```
# WikiRev 23R2
While this revision will be not going to be as big as the one i planned on #82, there will be some big changes to the overall structure of the wiki.

## Highlights
### Core
- Overall file structure (`master` branch) of the wiki will have a major refactor.
- New wiki structure planned to declutter useless sections, most pages having their content be changed, modified, deleted, combined, or relocated.
- Simpler, "intuitive" approach on some sections.
  - Sub-folders labeled as "LM" on every folder will be containing the refactor on most of the wiki's content.

### Content
- Linux, WSA methods of installation.
- Removed some unnecessary files (unconfirmed)
  - `3PTYCLIENTS`
  - `117CC`
  - `CUSTOM-CONTROLS`
  - `DEBUG-LOG`
  - `DEFAULT-CONTROLS`
  - `ENV-VARS`
  - `FIRST-STEPS`
  - `INSTALL-MC
  - `JAVA-ARGS`
  - `MCVERS`
  - `NOTCH-FIX`
  - `SIGN-IN`
  - `ZINK`
- Merging, modifying, or relocation of some of the wiki's content.

### Display
Nothing is planned about UI changes for this wiki- *yet.*

2023-11-01 16:02 UTC, GaucovyAero approved these changes
ultimat

2025-01-06 17:33 UTC, alexytomi requested changes

2025-01-06 17:33 UTC, alexytomi commented on BUILD-FROM-SOURCE.md
> +# PLACEHOLDER COMMIT, will be removed, changed, or reverted as PR progresses.
Why would you even make a placeholder commit

2025-01-06 17:33 UTC, alexytomi commented on .gitattributes
> -*.markdown   text eol=lf
This forces git to convert line-endings to Unix LF (\n) instead of Windows CRLF (\r\n). This shouldn't be removed as this may cause problems during compilation when we unknowingly merge a commit with CRLF endings and something screws up in the compile process because of it because we run that on ubuntu-latest.

2025-01-06 17:33 UTC, alexytomi commented on .gitattributes
> -*.markdown   text eol=lf
This causes the rest of your .md commits to CRLF from what I can assume seeing as literally nothing changed but github says it does. This looks awful on the git blame.

2025-01-06 23:47 UTC, closed without merging