Update IOS.md
PojavLauncherTeam/pojavlauncherteam.github.io pull request #216
Opened 2024-11-19 23:42 UTC by hackcr1258

Added 3.0 Nightly build
Added a redirect to enable JIT

2024-11-20 00:02 UTC, CowSheep72 requested changes
"fixing" is not correct, use "fix"

2024-11-20 00:14 UTC, hackcr1258 commented
Edited on main branch

2024-11-20 00:19 UTC, CowSheep72 commented
also iirc 1.17+ has been supported even before 3.0, so you should probably replace "1.17+" with "1.20.5+"

2024-11-20 00:40 UTC, hackcr1258 commented
Edited

2025-01-06 17:18 UTC, alexytomi commented on changelogs/IOS.md
These aren't exactly features. More like bugfixes. 3.0 is also a placeholder, not a real version number.

2025-01-06 17:21 UTC, alexytomi commented on INSTALL.md
Probably needs to rework the entire format. Shoving URLs here seems haphazard and confusing for readers.

2025-01-06 17:21 UTC, alexytomi requested changes
Doesn't look like a good addition imo

2025-01-06 23:53 UTC, closed without merging